import type { DesignSystem } from "./types";

export const defaultDesignSystem: DesignSystem = {
  meta: {
    name: "",
    description: "",
  },
  colors: {
    primary: "#0f172a",
    primaryForeground: "#f8fafc",
    secondary: "#f1f5f9",
    secondaryForeground: "#0f172a",
    background: "#ffffff",
    foreground: "#0f172a",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#f1f5f9",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    border: "#e2e8f0",
    ring: "#94a3b8",
    custom: {},
  },
  typography: {
    fontFamilySans: "Inter, system-ui, sans-serif",
    fontFamilyMono: "JetBrains Mono, monospace",
    fontFamilySerif: "",
    scale: {
      xs: { size: "0.75rem", lineHeight: "1rem", weight: "400" },
      sm: { size: "0.875rem", lineHeight: "1.25rem", weight: "400" },
      base: { size: "1rem", lineHeight: "1.5rem", weight: "400" },
      lg: { size: "1.125rem", lineHeight: "1.75rem", weight: "400" },
      xl: { size: "1.25rem", lineHeight: "1.75rem", weight: "600" },
      "2xl": { size: "1.5rem", lineHeight: "2rem", weight: "700" },
      "3xl": { size: "1.875rem", lineHeight: "2.25rem", weight: "700" },
      "4xl": { size: "2.25rem", lineHeight: "2.5rem", weight: "800" },
    },
  },
  spacing: {
    baseUnit: 4,
    scale: {
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "8": "32px",
      "10": "40px",
      "12": "48px",
      "16": "64px",
      "20": "80px",
      "24": "96px",
    },
    borderRadius: {
      sm: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      full: "9999px",
    },
  },
  components: {
    preferredLibrary: "shadcn/ui",
    rules: [
      "Use semantic color tokens instead of hardcoded values",
      "All interactive elements must have visible focus states",
      "Buttons should use the Button component from the preferred library",
      "Form inputs should have associated labels",
    ],
    patterns: [],
  },
  layout: {
    maxWidth: "1280px",
    breakpoints: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    columns: 12,
    gutter: "24px",
    containerPadding: "16px",
    rules: [
      "Use responsive breakpoints for layout changes",
      "Content should be centered with max-width constraint",
    ],
  },
};
